# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kxmlgui' : '@latest'
    'frameworks/kdoctools' : '@latest'
    'frameworks/extra-cmake-modules': '@latest'

