# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kxmlgui' : '@latest-kf6'
    'frameworks/kdoctools' : '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kxmlgui' : '@latest'
    'frameworks/kdoctools' : '@latest'
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kio': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
